version: '3'

services:
  redis:
    image: "redis:alpine"

  web:
    container_name: currency_web
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/currency_code
    environment:
      - APP_ENV=dev
      - FIXER_API_KEY=<add env here>
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    container_name: currency_celery_worker
    build: .
    command: celery -A currency worker -l info
    volumes:
      - .:/currency_code
    environment:
      - APP_ENV=dev
    depends_on:
      - redis
      - web

  celery-beat:
    container_name: currency_celery_beat
    build: .
    command: celery -A currency beat -l info
    volumes:
      - .:/currency_code
    environment:
      - APP_ENV=dev
    depends_on:
      - redis
      - web

volumes:
  postgres_data: